# Ruby CircleCI 2.1 configuration file
version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-buster-node
    steps:
      - checkout
      - run:
          name: Which Bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Check migration up
          command: bundle exec sequel sqlite://db/database.db -m db/migrations
      - run:
          name: Check migration down
          command: bundle exec sequel sqlite://db/database.db -m db/migrations -M 0
      - run:
          name: Check seeds
          command: bundle exec sequel sqlite://db/database.db -m db/migrations && bundle exec ruby db/seed.rb
